// Generated by Rcpp::compileAttributes() style stubs. Do not edit by hand if you regenerate attributes.
#include <Rcpp.h>

using namespace Rcpp;

List compute_T_i_S_i(List tree, int node, NumericVector abundances);
List calculate_S_i_a_star(List tree, int node, NumericVector abundances);
List calculate_S_i_a(List tree, int node, NumericVector abundances, int curr_ancestor, double h, double l_i);
Rcpp::RObject calculate_DJ_i_a(List tree, int node, NumericVector abundances, int curr_ancestor, double h, double l_i, std::string index_letter, int q, bool individual);
List calculate_EJM_i_a(List tree, int node, NumericVector abundances, int curr_ancestor, double h, double l_i, std::string index_letter, int q, bool individual);
Rcpp::RObject calculate_integral(List tree, int node, int curr_ancestor, DataFrame S_i, NumericVector abundances, std::string index_letter, int q, bool individual);
Rcpp::RObject calculate_DJ_i(List tree, int node, NumericVector abundances, std::string index_letter, int q, bool individual);
Rcpp::RObject node_cpp(SEXP file, Rcpp::RObject node_abundances, std::string index_letter, int q, bool individual);
Rcpp::RObject long_star_cpp(SEXP file, Rcpp::RObject node_abundances, std::string mean_type, std::string index_letter, int q, bool individual);
List all_indices_cpp(SEXP file, Rcpp::RObject node_abundances);

RcppExport SEXP _TreeShapeIndices_compute_T_i_S_i(SEXP treeSEXP, SEXP nodeSEXP, SEXP abundancesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< int >::type node(nodeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type abundances(abundancesSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_T_i_S_i(tree, node, abundances));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _TreeShapeIndices_calculate_S_i_a_star(SEXP treeSEXP, SEXP nodeSEXP, SEXP abundancesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< int >::type node(nodeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type abundances(abundancesSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_S_i_a_star(tree, node, abundances));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _TreeShapeIndices_calculate_S_i_a(SEXP treeSEXP, SEXP nodeSEXP, SEXP abundancesSEXP, SEXP curr_ancestorSEXP, SEXP hSEXP, SEXP l_iSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< int >::type node(nodeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type abundances(abundancesSEXP);
    Rcpp::traits::input_parameter< int >::type curr_ancestor(curr_ancestorSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type l_i(l_iSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_S_i_a(tree, node, abundances, curr_ancestor, h, l_i));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _TreeShapeIndices_calculate_DJ_i_a(SEXP treeSEXP, SEXP nodeSEXP, SEXP abundancesSEXP, SEXP curr_ancestorSEXP, SEXP hSEXP, SEXP l_iSEXP, SEXP index_letterSEXP, SEXP qSEXP, SEXP individualSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< int >::type node(nodeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type abundances(abundancesSEXP);
    Rcpp::traits::input_parameter< int >::type curr_ancestor(curr_ancestorSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type l_i(l_iSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_letter(index_letterSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< bool >::type individual(individualSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_DJ_i_a(tree, node, abundances, curr_ancestor, h, l_i, index_letter, q, individual));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _TreeShapeIndices_calculate_EJM_i_a(SEXP treeSEXP, SEXP nodeSEXP, SEXP abundancesSEXP, SEXP curr_ancestorSEXP, SEXP hSEXP, SEXP l_iSEXP, SEXP index_letterSEXP, SEXP qSEXP, SEXP individualSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< int >::type node(nodeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type abundances(abundancesSEXP);
    Rcpp::traits::input_parameter< int >::type curr_ancestor(curr_ancestorSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type l_i(l_iSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_letter(index_letterSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< bool >::type individual(individualSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_EJM_i_a(tree, node, abundances, curr_ancestor, h, l_i, index_letter, q, individual));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _TreeShapeIndices_calculate_integral(SEXP treeSEXP, SEXP nodeSEXP, SEXP curr_ancestorSEXP, SEXP S_iSEXP, SEXP abundancesSEXP, SEXP index_letterSEXP, SEXP qSEXP, SEXP individualSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< int >::type node(nodeSEXP);
    Rcpp::traits::input_parameter< int >::type curr_ancestor(curr_ancestorSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type S_i(S_iSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type abundances(abundancesSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_letter(index_letterSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< bool >::type individual(individualSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_integral(tree, node, curr_ancestor, S_i, abundances, index_letter, q, individual));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _TreeShapeIndices_calculate_DJ_i(SEXP treeSEXP, SEXP nodeSEXP, SEXP abundancesSEXP, SEXP index_letterSEXP, SEXP qSEXP, SEXP individualSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< int >::type node(nodeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type abundances(abundancesSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_letter(index_letterSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< bool >::type individual(individualSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_DJ_i(tree, node, abundances, index_letter, q, individual));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _TreeShapeIndices_node_cpp(SEXP fileSEXP, SEXP node_abundancesSEXP, SEXP index_letterSEXP, SEXP qSEXP, SEXP individualSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    SEXP file(fileSEXP);
    Rcpp::RObject node_abundances(node_abundancesSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_letter(index_letterSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< bool >::type individual(individualSEXP);
    rcpp_result_gen = Rcpp::wrap(node_cpp(file, node_abundances, index_letter, q, individual));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _TreeShapeIndices_long_star_cpp(SEXP fileSEXP, SEXP node_abundancesSEXP, SEXP mean_typeSEXP, SEXP index_letterSEXP, SEXP qSEXP, SEXP individualSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    SEXP file(fileSEXP);
    Rcpp::RObject node_abundances(node_abundancesSEXP);
    Rcpp::traits::input_parameter< std::string >::type mean_type(mean_typeSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_letter(index_letterSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< bool >::type individual(individualSEXP);
    rcpp_result_gen = Rcpp::wrap(long_star_cpp(file, node_abundances, mean_type, index_letter, q, individual));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _TreeShapeIndices_all_indices_cpp(SEXP fileSEXP, SEXP node_abundancesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    SEXP file(fileSEXP);
    Rcpp::RObject node_abundances(node_abundancesSEXP);
    rcpp_result_gen = Rcpp::wrap(all_indices_cpp(file, node_abundances));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TreeShapeIndices_compute_T_i_S_i", (DL_FUNC) &_TreeShapeIndices_compute_T_i_S_i, 3},
    {"_TreeShapeIndices_calculate_S_i_a_star", (DL_FUNC) &_TreeShapeIndices_calculate_S_i_a_star, 3},
    {"_TreeShapeIndices_calculate_S_i_a", (DL_FUNC) &_TreeShapeIndices_calculate_S_i_a, 6},
    {"_TreeShapeIndices_calculate_DJ_i_a", (DL_FUNC) &_TreeShapeIndices_calculate_DJ_i_a, 9},
    {"_TreeShapeIndices_calculate_EJM_i_a", (DL_FUNC) &_TreeShapeIndices_calculate_EJM_i_a, 9},
    {"_TreeShapeIndices_calculate_integral", (DL_FUNC) &_TreeShapeIndices_calculate_integral, 8},
    {"_TreeShapeIndices_calculate_DJ_i", (DL_FUNC) &_TreeShapeIndices_calculate_DJ_i, 6},
    {"_TreeShapeIndices_node_cpp", (DL_FUNC) &_TreeShapeIndices_node_cpp, 5},
    {"_TreeShapeIndices_long_star_cpp", (DL_FUNC) &_TreeShapeIndices_long_star_cpp, 6},
    {"_TreeShapeIndices_all_indices_cpp", (DL_FUNC) &_TreeShapeIndices_all_indices_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_TreeShapeIndices(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}