# Generated by Rcpp::compileAttributes() style stubs. Do not edit by hand if you regenerate attributes.

compute_T_i_S_i <- function(tree, node, abundances) {
    .Call(`_TreeShapeIndices_compute_T_i_S_i`, tree, node, abundances)
}

calculate_S_i_a_star <- function(tree, node, abundances) {
    .Call(`_TreeShapeIndices_calculate_S_i_a_star`, tree, node, abundances)
}

calculate_S_i_a <- function(tree, node, abundances, curr_ancestor, h, l_i) {
    .Call(`_TreeShapeIndices_calculate_S_i_a`, tree, node, abundances, curr_ancestor, h, l_i)
}

calculate_DJ_i_a <- function(tree, node, abundances, curr_ancestor, h, l_i, index_letter, q, individual) {
    .Call(`_TreeShapeIndices_calculate_DJ_i_a`, tree, node, abundances, curr_ancestor, h, l_i, index_letter, q, individual)
}

calculate_EJM_i_a <- function(tree, node, abundances, curr_ancestor, h, l_i, index_letter, q, individual) {
    .Call(`_TreeShapeIndices_calculate_EJM_i_a`, tree, node, abundances, curr_ancestor, h, l_i, index_letter, q, individual)
}

calculate_integral <- function(tree, node, curr_ancestor, S_i, abundances, index_letter, q, individual) {
    .Call(`_TreeShapeIndices_calculate_integral`, tree, node, curr_ancestor, S_i, abundances, index_letter, q, individual)
}

calculate_DJ_i <- function(tree, node, abundances, index_letter = "D", q = 1, individual = FALSE) {
    .Call(`_TreeShapeIndices_calculate_DJ_i`, tree, node, abundances, index_letter, q, individual)
}

node_cpp <- function(file, node_abundances = NULL, index_letter = "D", q = 1, individual = FALSE) {
    .Call(`_TreeShapeIndices_node_cpp`, file, node_abundances, index_letter, q, individual)
}

long_star_cpp <- function(file, node_abundances = NULL, mean_type = "Star", index_letter = "D", q = 1, individual = FALSE) {
    .Call(`_TreeShapeIndices_long_star_cpp`, file, node_abundances, mean_type, index_letter, q, individual)
}

all_indices_cpp <- function(file, node_abundances = NULL) {
    .Call(`_TreeShapeIndices_all_indices_cpp`, file, node_abundances)
}
